# WhatATheme
markdown: kramdown

# URL of the Site
url: 'joemcd.ca'
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: Joe McDonald
# Description of the Site
description: My Personal Website
# URL of Image of the Site
site-image: /assets/images/meta.png
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: /assets/images/shoot_content.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/anotherpic.jpg

# https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: joemcd0224@gmail.com
# facebook_username: joemcdonald0224
# twitter_username: thedevslot
instagram_username: joe__mcd
linkedin_username: joemcd0224
github_username:  joe-mcdonald
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: /
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
# google-analytics: UA-163806439-1

# Disqus
# disqus-shortname: thedevslot

# Name of the Author
author-name: Joe McDonald
# URL for the Image of the Author
author-image: /assets/images/shoot_content.png
# 60 Words About the Author
author-about: Hello! I’m Joe, I am a software engineering student at the University of Victoria. Some of my hobbies include programming, running, skiing, golfing, and hanging out with friends.
author-about-short: Software Engineering Student at the University of Victoria
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/joe-mcdonald

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed
  - jekyll-redirect-from

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
